Translate ContactPage
ase-lab-space/ase-lab pull request #55
Opened 2022-11-11 10:12 UTC by tkt08

# 概要

ContactPageを一部英語対応しました

## その他

ラベルのところも後でやります。
苦戦しております、、、

2022-11-11 13:10 UTC, Damin3927 requested changes
ブランチのマージの向け先OK
ありがとうございます！

2022-11-11 13:10 UTC, Damin3927 commented on src/i18n/en-US/index.ts
> +  askMe: 'Write to us any questions, opinion and cooperation offers. We will get back to you as soon as possible.'
ここに書く場合、階層分けをしっかりしないと非常にわかりづらくなります。
例えば、これから100個以上のキーをベタ書きで書いていくとなると、どのキーがどのページに対応しているのかわからなくなります。
そのため、もしここに書くとしたとしても、
```javascript
export default {
  pages: {
    ContactPage: {
      askMe: 'hoge',
    },
  },
};
```
こんな感じで階層分けが必要となります。

それに加えて、わざわざディレクトリが分かれている`src/i18n/en-US/index.ts`に書くより、それぞれのSFC（.vueファイル）の中に書いた方が階層を分ける必要もないし最終的にわかりやすくなると思います。

```vue
<template>
  <h1>{{ t('hoge') }}</h1>
</template>

<i18n lang="yaml">
en:
  hoge: hoge
ja:
  hoge: ほげ
</i18n>

<script lang="ts">
import { defineComponent } from 'vue';
import { useI18n } from 'vue-i18n';

export default defineComponent({
  setup() {
    const { t } = useI18n();
    return {
      t,
    };
  },
});
</script>
```
（こんなイメージ）

2022-11-11 13:10 UTC, Damin3927 commented on src/i18n/en-US/index.ts
> +  askMe: 'Write to us any questions, opinion and cooperation offers. We will get back to you as soon as possible.'
上のSFCの書き方で、もう一度書いてみていただけますか？ 🙇‍♂️

2022-11-11 14:36 UTC, tkt08 commented on src/i18n/en-US/index.ts
> +  askMe: 'Write to us any questions, opinion and cooperation offers. We will get back to you as soon as possible.'
わかりました！

2022-11-12 06:38 UTC, tkt08 commented on src/i18n/en-US/index.ts
> +  askMe: 'Write to us any questions, opinion and cooperation offers. We will get back to you as soon as possible.'
新しくpushしたんですけど見れてますか？

2022-11-12 07:55 UTC, tkt08 commented
新しく書き直したので確認お願いいたします。
（すいません、resolve conversationをクリックしてしまいました）

2022-11-16 11:20 UTC, Damin3927 reviewed
おおむねOKだと思います！

2022-11-17 03:46 UTC, Damin3927 approved these changes
ありがとうございます！

2022-11-17 03:46 UTC, merged