change notation
ase-lab-space/ase-lab pull request #77
Opened 2023-01-30 15:28 UTC by tkt08

# 概要

src/i18n/ja-JP/内を編集
CansatゼミからCanSatゼミに表記変更

## その他

2023-01-30 17:33 UTC, Damin3927 approved these changes
LGTM！

2023-01-30 17:34 UTC, Damin3927 requested changes
あ、こっちも直してもらうことって可能ですか？
https://github.com/ase-lab-space/ase-lab/blob/change-notation/src/i18n/en-US/seminars.ts#L10

2023-01-31 05:46 UTC, tkt08 commented
修正しました！

2023-01-31 07:29 UTC, Damin3927 approved these changes
ありがとうございます！

2023-01-31 07:29 UTC, merged